services:
  whatsapp-service-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: whatsapp-service-bot
    restart: unless-stopped
    ports:
      - "${PORT:-3000}:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
